package br.com.redesurftank.havalshisuku.models

enum class SharedPreferencesKeys(val key: String, val description: String) {
    DISABLE_MONITORING("disableMonitoring", "保持禁用分心驾驶监控"),
    CLOSE_WINDOW_ON_POWER_OFF("closeWindowOnPowerOff", "熄火时关闭车窗"),
    CLOSE_WINDOW_ON_FOLD_MIRROR("closeWindowOnFoldMirror", "收起后视镜时关闭车窗"),
    CLOSE_SUNROOF_ON_POWER_OFF("closeSunroofOnPowerOff", "熄火时关闭天窗"),
    CLOSE_SUNROOF_ON_FOLD_MIRROR("closeSunroofOnFoldMirror", "收起后视镜时关闭天窗"),
    CLOSE_WINDOWS_ON_SPEED("closeWindowsOnSpeed", "达到车速时关闭车窗"),
    CLOSE_SUNROOF_ON_SPEED("closeSunroofOnSpeed", "达到车速时关闭天窗"),
    CLOSE_SUNROOF_SUN_SHADE_ON_CLOSE_SUNROOF("closeSunroofSunShadeOnCloseSunRoof", "关闭天窗时收起天窗遮阳帘"),
    SET_STARTUP_VOLUME("setStartupVolume", "车辆通电时设置音量"),
    STARTUP_VOLUME("startupVolume", "通电时音量"),
    SPEED_THRESHOLD("speedThreshold", "自动关窗速度阈值"),
    SUNROOF_SPEED_THRESHOLD("sunroofSpeedThreshold", "自动关天窗速度阈值"),
    NIGHT_START_HOUR("nightStartHour", "夜晚开始时间"),
    NIGHT_START_MINUTE("nightStartMinute", "夜晚开始分钟"),
    NIGHT_END_HOUR("nightEndHour", "夜晚结束时间"),
    NIGHT_END_MINUTE("nightEndMinute", "夜晚结束分钟"),
    ENABLE_AUTO_BRIGHTNESS("enableAutoBrightness", "启用自动亮度调节"),
    AUTO_BRIGHTNESS_LEVEL_NIGHT("autoBrightnessLevelNight", "夜间自动亮度"),
    AUTO_BRIGHTNESS_LEVEL_DAY("autoBrightnessLevelDay", "白天自动亮度"),
    ENABLE_FRIDA_HOOKS("enableFridaHooks", "启用 Frida 钩子"),
    ENABLE_FRIDA_HOOK_SYSTEM_SERVER("enableFridaHookSystemServer", "在 System Server 中启用 Frida 钩子"),
    ENABLE_INSTRUMENT_PROJECTOR("enableInstrumentProjector", "在仪表盘投影数据"),
    ENABLE_INSTRUMENT_ODOMETER("enableInstrumentOdometer", "在仪表盘显示里程"),
    ENABLE_INSTRUMENT_REVISION_WARNING("enableInstrumentRevisionWarning", "在仪表盘显示保养提醒"),
    ENABLE_INSTRUMENT_ODOMETER_AND_REVISION("enableOdometerAndRevision", "在仪表盘显示里程与保养提醒"),
    ENABLE_INSTRUMENT_EV_BATTERY_PERCENTAGE("enableInstrumentEvBatteryPercentage", "在仪表盘显示 EV 电量百分比"),
    ENABLE_INSTRUMENT_CUSTOM_MEDIA_INTEGRATION("enableInstrumentCustomMediaIntegration", "在仪表盘显示自定义媒体信息"),
    ENABLE_CUSTOM_MENU("enableCustomMenu", "在仪表显示可用方向盘按键控制的自定义菜单"),
    INSTRUMENT_REVISION_KM("instrumentRevisionKm", "仪表盘保养提醒里程"),
    INSTRUMENT_REVISION_NEXT_DATE("instrumentRevisionNextDate", "仪表盘下次保养日期"),
    DISABLE_AVAS("disableAvas", "禁用 AVAS（低速车辆警示音系统）"),
    DISABLE_AVM_CAR_STOPPED("disableAvmCarStopped", "车辆静止时关闭 AVM 相机"),
    // ===== Debloat: desativa apps do sistema (OEM) que rodam e consomem RAM/CPU da multimídia =====
    // Reversível (pm install-existing) e reaplicado no boot por ServiceManager.ensureDebloatedSystemApps().
    DISABLE_NATIVE_NAVIGATION("disableNativeNavigation", "禁用原厂 Neusoft 导航"),
    DISABLE_NATIVE_VOICE("disableNativeVoice", "禁用原厂 iFlyTek 语音助手"),
    DISABLE_NATIVE_WEATHER("disableNativeWeather", "禁用原厂天气预报服务"),
    CAR_MONITOR_PROPERTIES("carMonitorProperties", "车辆监控属性"),
    BYPASS_SELF_INSTALLATION_INTEGRITY_CHECK("bypassSelfInstallationIntegrityCheck", "跳过安装完整性校验"),
    SELF_INSTALLATION_INTEGRITY_CHECK("selfInstallationIntegrityCheck", "安装完整性校验"),
    ADVANCE_USE("advanceUse", "高级模式"),
    CURRENT_USER("currentUser", "当前用户"),
    LAST_CLUSTER_AC_CONFIG("lastClusterAcConfig", "仪表上次空调配置"),
    DISABLE_BLUETOOTH_ON_POWER_OFF("disableBluetoothOnPowerOff", "熄火时关闭蓝牙"),
    DISABLE_HOTSPOT_ON_POWER_OFF("disableHotspotOnPowerOff", "熄火时关闭热点"),
    BLUETOOTH_STATE_ON_POWER_OFF("bluetoothStateOnPowerOff", "熄火时蓝牙状态"),
    ENABLE_SEAT_VENTILATION_ON_AC_ON("enableSeatVentilationOnAcOn", "开启空调时联动驾驶员座椅通风"),
    ENABLE_STEERING_WHEEL_CUSTOM_BUTTONS("enableSteeringWheelCustomButtons", "启用方向盘自定义按键"),
    PERSISTENT_BOTTOM_BAR("enable_persistent_bottom_bar", "启用常驻底部快捷栏（Android 9）"),
    STEERING_WHEEL_CUSTOM_BUTON_1_ACTION("steeringWheelCustomButon1Action", "方向盘自定义按键 1 动作"),
    STEERING_WHEEL_CUSTOM_BUTON_2_ACTION("steeringWheelCustomButon2Action", "方向盘自定义按键 2 动作"),
    STEERING_WHEEL_CUSTOM_BUTON_1_ACTION_ORIGINAL("steeringWheelCustomButon1ActionOriginal", "方向盘自定义按键 1 原始动作"),
    STEERING_WHEEL_CUSTOM_BUTON_2_ACTION_ORIGINAL("steeringWheelCustomButon2ActionOriginal", "方向盘自定义按键 2 原始动作"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_1("steeringWheelOpenAppPackageButton1", "方向盘自定义按键 1 打开的应用包名"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_2("steeringWheelOpenAppPackageButton2", "方向盘自定义按键 2 打开的应用包名"),
    STEERING_WHEEL_CUSTOM_BUTON_1_ACTION_DOUBLE("steeringWheelCustomButon1ActionDouble", "方向盘自定义按键 1 动作（双击）"),
    STEERING_WHEEL_CUSTOM_BUTON_2_ACTION_DOUBLE("steeringWheelCustomButon2ActionDouble", "方向盘自定义按键 2 动作（双击）"),
    STEERING_WHEEL_CUSTOM_BUTON_1_ACTION_LONG("steeringWheelCustomButon1ActionLong", "方向盘自定义按键 1 动作（长按）"),
    STEERING_WHEEL_CUSTOM_BUTON_2_ACTION_LONG("steeringWheelCustomButon2ActionLong", "方向盘自定义按键 2 动作（长按）"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_1_DOUBLE("steeringWheelOpenAppPackageButton1Double", "方向盘按键 1 打开的应用包名（双击）"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_2_DOUBLE("steeringWheelOpenAppPackageButton2Double", "方向盘按键 2 打开的应用包名（双击）"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_1_LONG("steeringWheelOpenAppPackageButton1Long", "方向盘按键 1 打开的应用包名（长按）"),
    STEERING_WHEEL_OPEN_APP_PACKAGE_BUTTON_2_LONG("steeringWheelOpenAppPackageButton2Long", "方向盘按键 2 打开的应用包名（长按）"),
    STEERING_WHEEL_CLIMATE_COMMAND_BUTTON_1("steeringWheelClimateCommandButton1", "方向盘自定义按键 1 空调指令"),
    STEERING_WHEEL_CLIMATE_COMMAND_BUTTON_2("steeringWheelClimateCommandButton2", "方向盘自定义按键 2 空调指令"),
    LAST_CLUSTER_SCREEN("lastClusterScreen", "仪表上次显示的屏幕"),
    LAST_CLUSTER_MENU_ITEM("lastClusterMenuItem", "仪表主菜单上次选中的项"),
    ENABLE_MAX_AC_ON_UNLOCK("enableMaxAcOnUnlock", "车辆通电且温度高于阈值时启用 Max AC"),
    MAX_AC_ON_UNLOCK_THRESHOLD("maxAcOnUnlockThreshold", "触发 Max AC 的温度阈值"),
    MAX_AC_TARGET_TEMP("maxAcTargetTemp", "Max AC 目标温度"),
    MAX_AC_TIMEOUT("maxAcTimeout", "Max AC 自动关闭时长（分钟）"),
    ENABLE_OPEN_SUNROOF_CURTAIN_ON_START("enableOpenSunroofCurtainOnStart", "通电时自动打开天窗遮阳帘"),
    OPEN_SUNROOF_CURTAIN_START_HOUR("openSunroofCurtainStartHour", "打开遮阳帘开始时间"),
    OPEN_SUNROOF_CURTAIN_START_MINUTE("openSunroofCurtainStartMinute", "打开遮阳帘开始分钟"),
    OPEN_SUNROOF_CURTAIN_END_HOUR("openSunroofCurtainEndHour", "打开遮阳帘结束时间"),
    OPEN_SUNROOF_CURTAIN_END_MINUTE("openSunroofCurtainEndMinute", "打开遮阳帘结束分钟"),
    OPEN_SUNROOF_CURTAIN_MAX_TEMP("openSunroofCurtainMaxTemp", "打开遮阳帘的室外最高温度"),
    PENDING_RESET_TARGET_VERSION("pendingResetTargetVersion", "返回稳定通道时的数据重置目标版本"),
    SHOW_BETA_UPDATES("showBetaUpdates", "显示测试版通道更新"),
    DISPLAY_APP_CONFIGS("displayAppConfigs", "副屏应用配置"),
    ENABLE_VIRTUAL_CLUSTER("enableVirtualCluster", "在仪表盘启用虚拟仪表"),
    VIRTUAL_CLUSTER_DISPLAY_ID("instrumentMaskDisplayId", "虚拟仪表屏幕 ID（固定为 3）"),
    CURRENT_CLUSTER_TEMPLATE("currentClusterTemplate", "当前仪表模板"),
    CURRENT_CLUSTER_DISPLAY("currentClusterDisplay", "仪表显示模式"),
    DEFAULT_DISPLAY_APP_PACKAGE("defaultDisplayAppPackage", "仪表启动时默认打开的应用包名"),
    INSTRUMENT_REVISION_HISTORY("instrumentRevisionHistory", "已完成保养历史"),
    VIRTUAL_CLUSTER_THEME("virtualClusterTheme", "虚拟仪表主题"),
    VIRTUAL_CLUSTER_NIGHT_MODE("virtualClusterNightMode", "虚拟仪表夜间模式"),
    CLUSTER_FUEL_DISPLAY_UNIT("clusterFuelDisplayUnit", "仪表燃油显示单位"),
    PERSISTENT_BOTTOM_BAR_OVERSCAN("persistentBottomBarOverscan", "底栏底部留白调整（overscan）"),
    CUSTOM_THEME_REPO_URL_PROD("customThemeRepoUrlProd", "主题仓库地址（正式）"),
    CUSTOM_THEME_REPO_URL_DEV("customThemeRepoUrlDev", "主题仓库地址（开发）"),
    CUSTOM_THEME_REPO_ENV("customThemeRepoEnv", "主题仓库环境（正式/开发）"),
    ACTIVE_CUSTOM_THEME("activeCustomTheme", "当前动态主题"),
    BOTTOM_BAR_AUTO_HIDE("bottomBarAutoHide", "30 秒无操作后自动隐藏底栏"),
    BOTTOM_BAR_OVERRIDES("bottomBarOverrides", "已保存应用覆盖配置（JSON）"),
    ENABLE_SPEED_ADJUSTMENT("enableSpeedAdjustment", "在仪表启用车速校准"),
    SPEED_ADJUSTMENT_OFFSET("speedAdjustmentOffset", "车速校准系数（%）"),
    ALWAYS_USE_THEME_DIMENSIONS("alwaysUseThemeDimensions", "应用始终使用主题尺寸"),
    TRIP_CONSISTENCY_CLUSTER_ACTIVE("tripConsistencyClusterActive", "在仪表显示低调的行程分析指示"),
    TRIP_CONSISTENCY_CLUSTER_SCORE("tripConsistencyClusterScore", "在仪表实时显示一致性评分")
}
